import Head from 'next/head'
import Footer from '../components/Footer'
import '../styles/globals.css'


const MyApp = ({ Component, pageProps }) => {
  return (
    <div className="container">
      <Head>
        <title>Forgetful Notes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} />
      <Footer />
    </div>
  )
}

export default MyApp;
